In [6]:
import numpy as np

In [10]:
test_array = np.array([1,2,3]) #一维数组
print(test_array)

[1 2 3]


In [18]:
test_2dimension = np.array(([1,2,3],[4,5,6])) #二维数组
print(test_2dimension)  
print("数据类型", type(test_2dimension))           #打印数组数据类型  
print("数组元素数据类型：", test_2dimension.dtype) #打印数组元素数据类型  
print("数组大小：", test_2dimension.size)      #打印数组尺寸，即数组元素总数  
print("数组形状：", test_2dimension.shape)         #打印数组形状  
print("数组的维度数目", test_2dimension.ndim)      #打印数组的维度数目 
print("每个元素所占的字节数", test_2dimension.itemsize)  #每个元素所占的字节数

[[1 2 3]
 [4 5 6]]
数据类型 <class 'numpy.ndarray'>
数组元素数据类型： int32
数组大小： 6
数组形状： (2, 3)
数组的维度数目 2
每个元素所占的字节数 4


In [19]:
test_3dimension = np.array((([1,2,3],[4,5,6]),([1,2,3],[4,5,6]))) #二维数组
print(test_dimension)  
print("数组大小：", test_dimension.size)      #打印数组尺寸，即数组元素总数  
print("数组形状：", test_dimension.shape)         #打印数组形状  
print("数组的维度数目", test_dimension.ndim)      #打印数组的维度数目 
print("每个元素所占的字节数", test_dimension.itemsize)  #每个元素所占的字节数

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
数据类型 <class 'numpy.ndarray'>
数组元素数据类型： int32
数组大小： 12
数组形状： (2, 2, 3)
数组的维度数目 3
每个元素所占的字节数 4
